name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/ci.yml'
  workflow_call:

jobs:
  ci:
    name: Build & Check
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: rm -rf node_modules package-lock.json && npm install

      - name: Linting
        run: npm run lint

      - name: Run Format check
        run: npm run format:check

      - name: Prisma Check
        run: npm run validate

      - name: Prisma Generate
        run: npm run generate

      - name: Run type checks
        run: npm run check-types

      - name: Build all packages
        run: npm run build
