name: Pipeline (Quality & Staging)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

jobs:
  ci-cd:
    name: Build, Check & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Run Format check
        run: npm run format:check

      - name: Prisma Check
        run: npm run validate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: Prisma Generate
        run: npm run generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: Run type checks
        run: npm run check-types

      - name: Build all packages
        run: npm run build

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Admin image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/admin/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-admin:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-admin:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Backend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-backend:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-turbo-kit-frontend:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Trigger Dokploy Admin Deployment
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     curl -X 'POST' \
      #     '${{ secrets.DOKPLOY_DOMAIN }}/api/application.deploy' \
      #     -H 'accept: application/json' \
      #     -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
      #     -H 'Content-Type: application/json' \
      #     -d '{
      #          "applicationId": "${{ secrets.DOKPLOY_ADMIN_APP_ID }}"
      #       }'

      # - name: Trigger Dokploy Backend Deployment
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     curl -X 'POST' \
      #     '${{ secrets.DOKPLOY_DOMAIN }}/api/application.deploy' \
      #     -H 'accept: application/json' \
      #     -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
      #     -H 'Content-Type: application/json' \
      #     -d '{
      #          "applicationId": "${{ secrets.DOKPLOY_BACKEND_APP_ID }}"
      #       }'

      # - name: Trigger Dokploy Frontend Deployment
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     curl -X 'POST' \
      #     '${{ secrets.DOKPLOY_DOMAIN }}/api/application.deploy' \
      #     -H 'accept: application/json' \
      #     -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
      #     -H 'Content-Type: application/json' \
      #     -d '{
      #          "applicationId": "${{ secrets.DOKPLOY_FRONTEND_APP_ID }}"
      #       }'
